name: Deploy Frontend to VPS

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Install dependencies and prepare environment.ts
        run: |
          npm ci
          cp src/environments/environment.ts.template src/environments/environment.ts
          sed -i "s|REPLACE_API_URL|${{ secrets.ENV_API_URL }}|" src/environments/environment.ts
          sed -i "s|REPLACE_SUPABASE_URL|${{ secrets.ENV_SUPABASE_URL }}|" src/environments/environment.ts
          sed -i "s|REPLACE_SUPABASE_ANON_KEY|${{ secrets.ENV_SUPABASE_ANON_KEY }}|" src/environments/environment.ts

      - name: Build Angular
        run: npm run build -- --configuration=production

      - name: Disable host key checking (TEMPORAL)
        run: |
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Deploy to VPS via rsync
        run: |
          rsync -avz --delete dist/frontend-active-english/browser/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.DEPLOY_PATH }}/
